name: Request Pokemon
description: Add Pokemon Requests Here
labels: "Pokemon Request"
projects: "AceGaming17/1"
assignees: AceGaming17
body:
  - type: input
    id: username
    attributes:
      label: TikTok Username
      description: Please input your TikTok handle and your display name in parenthesis.
      placeholder: "@example (Example)"
    validations:
      required: true
  - type: dropdown
    id: shiny
    attributes:
      label: Is the requested Pokemon a Shiny?
      description: Shinies are variants of Pokemon that have a different colorway, but are more difficult to find. Because shinies are more difficult, any non shiny Pokemon requests are a higher priority.
      options:
        - label: Yеs
        - label: Nо
    validations:
      required: true
  - type: dropdown
    id: alpha
    attributes:
      label: Is the requested Pokemon an Alpha?
      description: Alphas are variants of Pokemon that are larger than regular Pokemon and have better stats. They are not that hard to find, but Shiny Alphas (Shalphas) can be extremely difficult to look for. 
      options:
        - label: Yеs
        - label: Nо
    validations:
      required: true
  - type: input
    id: pokemon
    attributes:
      label: Pokemon Requested
      description: Please give me the name of the Pokemon that you're requesting. Please don't request any legendary or mythical Pokemon. Your request will be ignored if you do so.
    validations:
      required: true
  - type: dropdown
    id: gender
    attributes:
      label: Gender Choice
      description: Most Pokemon come with 2 genders, with some having 1 and some having nоne. Some Pokemon also have unique styles depending on their gender.
      options:
      - Doesn't Matter
      - Male
      - Female
      - Nоne
    validations: 
      required: true
  - type: dropdown
    id: ball
    attributes:
      label: Poke Ball Choice
      description: Please input which type of Poke Ball you would like for me to use when I catch your requested Pokemon. If you don't have a preference, I will use a Poke Ball. Master Ball is not present for obvious reasons.
      options:
      - Poke Ball
      - Great Ball
      - Ultra Ball
      - Quick Ball
      - Fast Ball
      - Lure Ball
      - Level Ball
      - Heavy Ball
      - Dive Ball
      - Net Ball
      - Luxury Ball
      - Nest Ball
      - Timer Ball
      - Dusk Ball
      - Premier Ball
      - Repeat Ball
      - Heal Ball
    validations: 
      required: true
